export const zones = [
  {
    name: "Jalipa",
    factors: {
      demografia: 65,
      movilidad: 84,
      salud: 37,
      competencia: 5,
      riesgo: 41,
      costos: 97,
    },
    predictedRoi: 56.17,
  },
  {
    name: "Tapeixtles",
    factors: {
      demografia: 63,
      movilidad: 51,
      salud: 10,
      competencia: 100,
      riesgo: 100,
      costos: 10,
    },
    predictedRoi: 54.57,
  },
  {
    name: "Santiago",
    factors: {
      demografia: 76,
      movilidad: 69,
      salud: 0,
      competencia: 98,
      riesgo: 74,
      costos: 47,
    },
    predictedRoi: 54.49,
  },
  {
    name: "Centro",
    factors: {
      demografia: 32,
      movilidad: 62,
      salud: 100,
      competencia: 16,
      riesgo: 41,
      costos: 10,
    },
    predictedRoi: 48.53,
  },
  {
    name: "Valle de las Garzas",
    factors: {
      demografia: 55,
      movilidad: 60,
      salud: 20,
      competencia: 58,
      riesgo: 50,
      costos: 84,
    },
    predictedRoi: 47.86,
  },
  {
    name: "Las Brisas",
    factors: {
      demografia: 24,
      movilidad: 67,
      salud: 35,
      competencia: 0,
      riesgo: 26,
      costos: 100,
    },
    predictedRoi: 42.89,
  },
  {
    name: "El Colomo",
    factors: {
      demografia: 15,
      movilidad: 7,
      salud: 52,
      competencia: 61,
      riesgo: 23,
      costos: 77,
    },
    predictedRoi: 26.27,
  },
  {
    name: "Salagua",
    factors: {
      demografia: 58,
      movilidad: 21,
      salud: 4,
      competencia: 100,
      riesgo: 4,
      costos: 0,
    },
    predictedRoi: 22.83,
  },
];
